### ISSUE TITLE
NOAA RNC is dead, long live ENC

### ISSUE THREAD

**Issue by free-x** [wellenvogel/avnav-mapproxy-plugin#11]
Hi @wellenvogel ,

tileservice for NOAA RNC (mbtiles) is dead 
https://github.com/wellenvogel/avnav/issues/219#issuecomment-1127806391

https://nauticalcharts.noaa.gov/updates/coast-survey-to-shut-down-the-raster-navigational-chart-tile-service-and-other-related-services/

in the meantime ENC is available. 
In the attachment is corresponding mapproxy configuration yaml
[noaaenc.yaml.txt](https://github.com/wellenvogel/avnav-mapproxy-plugin/files/8706633/noaaenc.yaml.txt)

Regards
free-x

**Comment by wellenvogel** [comment]
Cool. Many thanks.
