### ISSUE TITLE
Problems with noaa source

### ISSUE THREAD

**Issue by wellenvogel** [wellenvogel/avnav-mapproxy-plugin#8]
There was an issue on AvNav that basically turns out to be an issue of the mapproxy plugin:
https://github.com/wellenvogel/avnav/issues/176
To track any changes I just create this issue.

**Comment by free-x** [comment]
@wellenvogel @mgrouch
Could you try this fix?
https://github.com/free-x/avnav-mapproxy-plugin/commit/5c9473060c04930e2d12be521c0a8bc90471f7a5

**Comment by wellenvogel** [comment]
closed with 20220108
